//
//  Languages.swift
//  Langu.ag
//
//  Created by Huijing on 18/12/2016.
//  Copyright © 2016 Huijing. All rights reserved.
//

import Foundation


class Languages{

    var language_names: [String] = []
    static let LANGUAGE_ALL = "all_languages"

    init(){


        language_names.append("Abbruzzese")
        language_names.append("Afrikaans")
        language_names.append("Albanian")
        language_names.append("Alsatian")
        language_names.append("Amharic")
        language_names.append("Arabic (Classical)")
        language_names.append("Arabic (Egyptian)")
        language_names.append("Arabic (Lebanese)")
        language_names.append("Arabic (Modern Standard)")
        language_names.append("Arabic (Moroccan)")
        language_names.append("Armenian")
        language_names.append("Assamese")
        language_names.append("Australian English")
        language_names.append("Aymara")
        language_names.append("Azeri")
        language_names.append("Basque")
        language_names.append("Belorussian")
        language_names.append("Bengali")
        language_names.append("Berber (Tamazight)")
        language_names.append("Bosnian")
        language_names.append("Brazilian Portuguese")
        language_names.append("Breton")
        language_names.append("Bulgarian")
        language_names.append("Burmese")
        language_names.append("Canadian English")
        language_names.append("Canadian French")
        language_names.append("Cantonese")
        language_names.append("Catalan")
        language_names.append("Cebuano")
        language_names.append("Chibemba")
        language_names.append("Chichewa")
        language_names.append("Chinese (Mandarin)")
        language_names.append("Chuvash")
        language_names.append("Cornish")
        language_names.append("Corsican")
        language_names.append("Croatian")
        language_names.append("Czech")
        language_names.append("Danish")
        language_names.append("Dari")
        language_names.append("Dutch")
        language_names.append("Dzongkha")
        language_names.append("English")
        language_names.append("English (American)")
        language_names.append("English (Cockney)")
        language_names.append("English (Indian)")
        language_names.append("English (Scottish)")
        language_names.append("Esperanto")
        language_names.append("Estonian")
        language_names.append("Faroese")
        language_names.append("Farsi")
        language_names.append("Fijian")
        language_names.append("Finnish")
        language_names.append("Flemish")
        language_names.append("French")
        language_names.append("Frisian")
        language_names.append("Galician")
        language_names.append("Georgian")
        language_names.append("German")
        language_names.append("Greek")
        language_names.append("Greenlandic")
        language_names.append("Gujarati")
        language_names.append("Haitian Creole")
        language_names.append("Hausa")
        language_names.append("Hawaiian")
        language_names.append("Hebrew")
        language_names.append("Hindi")
        language_names.append("Hungarian")
        language_names.append("Icelandic")
        language_names.append("Igbo")
        language_names.append("Ilocano")
        language_names.append("Indonesian")
        language_names.append("Irish")
        language_names.append("Italian")
        language_names.append("Japanese")
        language_names.append("Javanese")
        language_names.append("Jerriais")
        language_names.append("Kachchi")
        language_names.append("Kannada")
        language_names.append("Kazakh")
        language_names.append("Khmer")
        language_names.append("Kinyarwanda (Rwanda)")
        language_names.append("Kirghiz")
        language_names.append("Klingon")
        language_names.append("Korean")
        language_names.append("Kurdish")
        language_names.append("Kurdish (Kurmanji)")
        language_names.append("Lao")
        language_names.append("Latin")
        language_names.append("Latin American Spanish")
        language_names.append("Latvian")
        language_names.append("Lingala")
        language_names.append("Lithuanian")
        language_names.append("Luganda")
        language_names.append("Luxembourgish")
        language_names.append("Macedonian")
        language_names.append("Malagasy")
        language_names.append("Malay")
        language_names.append("Malayalam")
        language_names.append("Maltese")
        language_names.append("Manx")
        language_names.append("Maori")
        language_names.append("Marathi")
        language_names.append("Mongolian")
        language_names.append("Navajo")
        language_names.append("Nepali")
        language_names.append("Norwegian")
        language_names.append("Occitan")
        language_names.append("Oriya")
        language_names.append("Oromo")
        language_names.append("Papiamento")
        language_names.append("Pashto")
        language_names.append("Pidgin (Nigerian)")
        language_names.append("Pidgin (Papua New Guinea)")
        language_names.append("Polish")
        language_names.append("Portuguese")
        language_names.append("Provencal")
        language_names.append("Punjabi")
        language_names.append("Quechua")
        language_names.append("Romanian")
        language_names.append("Romansh")
        language_names.append("Russian")
        language_names.append("Saami")
        language_names.append("Samoan")
        language_names.append("Sardinian")
        language_names.append("Scots")
        language_names.append("Scottish Gaelic")
        language_names.append("Serbian")
        language_names.append("Sesotho (Southern)")
        language_names.append("Shona")
        language_names.append("Sicilian")
        language_names.append("Sindhi")
        language_names.append("Sinhala")
        language_names.append("Slovak")
        language_names.append("Slovenian")
        language_names.append("Somali")
        language_names.append("Spanish")
        language_names.append("Spanish (Argentinian)")
        language_names.append("Swahili")
        language_names.append("Swedish")
        language_names.append("Swiss German")
        language_names.append("Tagalog")
        language_names.append("Tajiki")
        language_names.append("Tamil")
        language_names.append("Telugu")
        language_names.append("Thai")
        language_names.append("Tibetan")
        language_names.append("Tigrinya")
        language_names.append("Tswana")
        language_names.append("Turkish")
        language_names.append("Turkmen")
        language_names.append("Ukrainian")
        language_names.append("Urdu")
        language_names.append("Uzbek")
        language_names.append("Vietnamese")
        language_names.append("Welsh")
        language_names.append("Wolof")
        language_names.append("Xhosa")
        language_names.append("Yiddish")
        language_names.append("Yoruba")
        language_names.append("Zulu")


    }

}
